all:
	@cd rtsp_server; make
	@cd rtsp_client; make
	@cd mp4_format; make
	@cd audio_mix; make
	@cd kplayer; make

clean:
	@cd rtsp_server; make clean
	@cd rtsp_client; make clean
	@cd mp4_format; make clean
	@cd kplayer; make clean