import os
import sys

# add building.py path
sys.path = sys.path + [os.path.join('..','..','..','rt-smart','tools')]
from building import *

BuildApplication('stress_mem', 'SConscript', usr_root='../../../rt-smart/userapps')
