snd-soc-canaan-k230-audio-objs := canaan_k230_audio.o
obj-$(CONFIG_SND_SOC_CANAAN_K230_AUDIO) += snd-soc-canaan-k230-audio.o

snd-soc-canaan-k230-inno-objs := canaan_k230_inno.o audio_muxpin_ctrl.o muxpin_reg_ctl.o

obj-$(CONFIG_SND_SOC_CANAAN_K230_INNO) += snd-soc-canaan-k230-inno.o


