all:
	@cd rt-smart; make
	@cd sample_mcm; make
	@cd sample_venc; make
	@cd sample_vdec; make
	@cd sample_virtual_vio; make
	@cd sample_vdss; make
	@cd sample_vicap_dump; make
	@cd camera; make
	@cd sample_vicap_dump_lite; make
	@cd sample_vicap; make
	@cd sample_audio; make
	@cd sample_vo; make
	@cd sample_dpu_uvc; make
	@cd sample_yuv_sensor; make
clean:
	@cd rt-smart; make clean
	@cd sample_mcm; make clean
	@cd sample_venc; make clean
	@cd sample_vdec; make clean
	@cd sample_virtual_vio; make clean
	@cd sample_vdss; make clean
	@cd sample_vicap_dump; make clean
	@cd camera; make clean
	@cd sample_vicap_dump_lite; make clean
	@cd sample_vicap; make clean
	@cd sample_audio; make clean
	@cd sample_vo; make clean
	@cd sample_dpu_uvc; make clean
	@cd sample_yuv_sensor; make clean
