import os
import sys

# add building.py path
sys.path = sys.path + [os.path.join('..','..','..','tools')]
from building import *

BuildApplication('backtrace_utest', 'SConscript', usr_root = '../../..')
