# SPDX-License-Identifier: GPL-2.0
#
# Canaan AES-GCM Makefile
#
obj-$(CONFIG_CRYPTO_DEV_KENDRYTE_CRYP) += kendryte_crypto.o
kendryte_crypto-objs := kendryte-aes.o

obj-$(CONFIG_CRYPTO_DEV_KENDRYTE_HASH) += kendryte_hash.o
kendryte_hash-objs := kendryte-hash.o

obj-$(CONFIG_CRYPTO_DEV_KENDRYTE_RSA) += kendryte_rsa.o
kendryte_rsa-objs := kendryte-rsa.o