/**
 * @file      pufs_sp38a_regs.h
 * @brief     PUFsecurity SP38A register definition
 * @copyright 2020 PUFsecurity
 */
/* THIS SOFTWARE IS SUPPLIED BY PUFSECURITY ''AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. TO THE FULLEST
 * EXTENT ALLOWED BY LAW, PUFSECURITY'S TOTAL LIABILITY ON ALL CLAIMS IN
 * ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES,
 * IF ANY, THAT YOU HAVE PAID DIRECTLY TO PUFSECURITY FOR THIS SOFTWARE.
 */

#ifndef __PUFS_SP38A_REGS_H__
#define __PUFS_SP38A_REGS_H__

#ifdef __cplusplus
extern "C" {
#endif

//----------------------REGISTER STRUCT-------------------------------------//

struct pufs_sp38a_regs
{
    volatile uint32_t version;
    volatile uint32_t interrupt;
    volatile uint32_t feature;
    uint32_t _pad1;
    volatile uint32_t status;
    uint32_t _pad2;
    volatile uint32_t cfg;
};

//----------------------REGISTER BIT MASKS----------------------------------//
#define SP38A_INTRPT_INTRPT_ST_MASK     0x00000001
#define SP38A_INTRPT_INTRPT_EN_MASK     0x00010000
#define SP38A_FEATURE_ECB_CLR_MASK      0x00000001
#define SP38A_FEATURE_CFB_MASK          0x00000002
#define SP38A_FEATURE_OFB_MASK          0x00000004
#define SP38A_FEATURE_CBC_CLR_MASK      0x00000008
#define SP38A_FEATURE_CBC_CS1_MASK      0x00000010
#define SP38A_FEATURE_CBC_CS2_MASK      0x00000020
#define SP38A_FEATURE_CBC_CS3_MASK      0x00000040
#define SP38A_FEATURE_CTR_MASK          0x00000080
#define SP38A_FEATURE_ENC_MASK          0x00000100
#define SP38A_FEATURE_DEC_MASK          0x00000200
#define SP38A_STATUS_BUSY_MASK          0x00000001
#define SP38A_STATUS_RESP_MASK          0xfffffffe
#define SP38A_STATUS_ERROR_MASK         0xfffff0c0
#define SP38A_CFG_BC_TYPE_MASK          0x00000003
#define SP38A_CFG_MODE_MASK             0x000000f0
#define SP38A_CFG_ENCRYPT_MASK          0x00000100

#ifdef __cplusplus
} // closing brace for extern "C"
#endif

#endif /*__PUFS_SP38A_REGS_H__*/
