#!/bin/sh


# Stop all init scripts in /etc/init.d
# executing them in reversed numerical order.
#

for i in $(ls -r /etc/init.d/S??*) ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set stop
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i stop
	    ;;
   esac
done

rmmod r8152
umount /sharefs
rmmod sdhci-of-kendryte
rmmod sdhci-pltfm
rmmod sdhci
rmmod mmc_block
rmmod mmc_core

killall sharefs
rmmod k_ipcm
