#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#

# echo "before install k_ipcm ..."
# /app/peephole_device/peephole_device -t
cd /mnt
insmod k_ipcm.ko
cd -
# echo "after install k_ipcm ..."
# /app/peephole_device/peephole_device -t

# for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
#     [ ! -f "$i" ] && continue

#     case "$i" in
#	*.sh)
#	    # Source shell script for speed.
#	    (
#		trap - INT QUIT TSTP
#		set start
#		. $i
#	    )
#	    ;;
#	*)
#	    # No sh extension, so fork subprocess.
#	    $i start
#	    ;;
#   esac
# done

/etc/init.d/S01syslogd start
/etc/init.d/S02klogd start
# /etc/init.d/S10mdev start
/etc/init.d/S20urandom start

cat /etc/version/release_version

cd /mnt
./sharefs &
cd -

insmod /lib/modules/5.10.4/kernel/drivers/net/usb/r8152.ko && /etc/init.d/S40network start && /etc/init.d/S50telnet start &

# TODO, FIXME, pathname hardcoded at the moment
# echo "start app ..."
nice -n -10 /app/peephole_device/peephole_device -s -m /sharefs/DCIM/video -j /sharefs/DCIM/snapshot &
