# SPDX-License-Identifier: GPL-2.0-only
canaan-drm-y := \
		canaan_drv.o \
		canaan_vo.o \
		canaan_crtc.o \
		canaan_plane.o

obj-$(CONFIG_DRM_CANAAN) += canaan-drm.o
obj-$(CONFIG_DRM_CANAAN_DSI) += canaan_dsi.o
