all:
	@cd sensor; make || exit 1
	@cd fft; make || exit 1
	@cd connector; make || exit 1
	@cd mediafreq; make || exit 1
	@cd pm; make || exit 1
clean:
	@cd sensor; make clean
	@cd fft; make clean
	@cd connector; make clean
	@cd mediafreq; make clean
	@cd pm; make clean