all:
	@cd rtsp_demo; make
	@cd rtsp_server; make
	@cd backchannel_client; make
	# @cd mp4_demuxer; make
	# @cd mp4_muxer; make
	@cd peephole_dev; make
	#@cd audio_mix_demo; make
	@cd kplayer_demo; make

clean:
	@cd rtsp_demo; make clean
	@cd rtsp_server; make clean
	@cd backchannel_client; make clean
	# @cd mp4_demuxer; make clean
	# @cd mp4_muxer; make clean
	@cd peephole_dev; make clean
	#@cd audio_mix_demo; make clean
	@cd kplayer_demo; make clean
