all:
	@cd rtsp_demo; make
	@cd rtsp_server; make
	@cd backchannel_client; make
	# @cd mp4_demuxer; make
	# @cd mp4_muxer; make
	#@cd audio_mix_demo; make
	@cd kplayer_demo; make
	@cd ws_discovery; make
	@cd rest_rpc; make
	@cd comm; make

clean:
	@cd rtsp_demo; make clean
	@cd rtsp_server; make clean
	@cd backchannel_client; make clean
	# @cd mp4_demuxer; make clean
	# @cd mp4_muxer; make clean
	#@cd audio_mix_demo; make clean
	@cd kplayer_demo; make clean
	@cd ws_discovery; make clean
	@cd rest_rpc; make clean
	@cd comm; make clean

