from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

CPPDEFINES = [ 'HAVE_CCONFIG_H' ]

group = DefineGroup('mmap_tc', src, depend = [''], CPPPATH = CPPPATH,
    CPPDEFINES = CPPDEFINES)

Return('group')
